name: CI/CD Pipeline

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches:
      - alpha
      - beta
      - canary
      - pre/rc

jobs:
  lint:
    uses: kurocado-studio/platform/.github/workflows/workflow.lint.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      monorepo: true

  test:
    needs: lint
    uses: kurocado-studio/platform/.github/workflows/workflow.test.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      monorepo: true

  release:
    needs: test
    uses: kurocado-studio/platform/.github/workflows/workflow.release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      branch_name: ${{ github.ref_name }}
      monorepo: true
